# Generated by Django 5.0.7 on 2024-08-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_created_at_blog_image_blog_view_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=7, max_length=150, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
