# Generated by Django 4.2.2 on 2024-09-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
