# Generated by Django 4.2.2 on 2024-09-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='last_datetime',
            field=models.DateTimeField(blank=True, help_text='Введите дату и время окончания рассылки', null=True, verbose_name='Дата и время окончания рассылки'),
        ),
    ]
