# Generated by Django 4.2.2 on 2024-09-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mailing_last_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='next_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время следующей отправки рассылки'),
        ),
    ]
