# Generated by Django 4.2.2 on 2024-09-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_mailing_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_active_status', 'Can active mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
